-- MySQL Script generated by MySQL Workbench
-- 2019년 11월 10일 (일) 오후 06시 49분 18초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`member_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`member_customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`member_customer` (
  `idmember_customer` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idmember_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mall` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mall` (
  `idmall` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `max_floor` INT NULL,
  PRIMARY KEY (`idmall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`floor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`floor` (
  `idfloor` INT NOT NULL AUTO_INCREMENT,
  `map` VARCHAR(20000) NULL,
  `size_width` INT NULL,
  `size_height` INT NULL,
  `mall_idmall` INT NOT NULL,
  `number` INT NULL,
  PRIMARY KEY (`idfloor`),
  INDEX `fk_floor_mall_idx` (`mall_idmall` ASC),
  CONSTRAINT `fk_floor_mall`
    FOREIGN KEY (`mall_idmall`)
    REFERENCES `mydb`.`mall` (`idmall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `floor_idfloor` INT NOT NULL,
  PRIMARY KEY (`idcategory`),
  INDEX `fk_category_floor1_idx` (`floor_idfloor` ASC),
  CONSTRAINT `fk_category_floor1`
    FOREIGN KEY (`floor_idfloor`)
    REFERENCES `mydb`.`floor` (`idfloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `iditem` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category_idcategory` INT NOT NULL,
  `quantity` INT NULL,
  `floor_idfloor` INT NOT NULL,
  PRIMARY KEY (`iditem`),
  INDEX `fk_item_category1_idx` (`category_idcategory` ASC),
  INDEX `fk_item_floor1_idx` (`floor_idfloor` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_floor1`
    FOREIGN KEY (`floor_idfloor`)
    REFERENCES `mydb`.`floor` (`idfloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`member_manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`member_manager` (
  `idmember_manager` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `mall_idmall` INT NOT NULL,
  PRIMARY KEY (`idmember_manager`),
  INDEX `fk_member_manager_mall1_idx` (`mall_idmall` ASC),
  CONSTRAINT `fk_member_manager_mall1`
    FOREIGN KEY (`mall_idmall`)
    REFERENCES `mydb`.`mall` (`idmall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shoppinglist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`shoppinglist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`shoppinglist` (
  `idshoppinglist` INT NOT NULL AUTO_INCREMENT COMMENT '																							',
  `member_customer_idmember_customer` INT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idshoppinglist`),
  INDEX `fk_shoppinglist_member_customer1_idx` (`member_customer_idmember_customer` ASC),
  INDEX `fk_shoppinglist_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_shoppinglist_member_customer1`
    FOREIGN KEY (`member_customer_idmember_customer`)
    REFERENCES `mydb`.`member_customer` (`idmember_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppinglist_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `useid` INT NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`idsession`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
