-- MySQL Script generated by MySQL Workbench
-- 2019년 10월 03일 (목) 오후 04시 11분 19초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`member_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_customer` (
  `idmember_customer` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idmember_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`headquarters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`headquarters` (
  `idheadquarters` INT NOT NULL COMMENT '	',
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`idheadquarters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mall` (
  `idmall` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `headquarters_idheadquarters` INT NOT NULL,
  PRIMARY KEY (`idmall`),
  INDEX `fk_mall_headquarters1_idx` (`headquarters_idheadquarters` ASC),
  CONSTRAINT `fk_mall_headquarters1`
    FOREIGN KEY (`headquarters_idheadquarters`)
    REFERENCES `mydb`.`headquarters` (`idheadquarters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`floor` (
  `idfloor` INT NOT NULL,
  `map` VARCHAR(20000) NULL,
  `size_width` INT NULL,
  `size_height` INT NULL,
  `mall_idmall` INT NOT NULL,
  PRIMARY KEY (`idfloor`),
  INDEX `fk_floor_mall_idx` (`mall_idmall` ASC),
  CONSTRAINT `fk_floor_mall`
    FOREIGN KEY (`mall_idmall`)
    REFERENCES `mydb`.`mall` (`idmall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `iditem` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`iditem`),
  INDEX `fk_item_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_manager` (
  `idmember_manager` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `mall_idmall` INT NOT NULL,
  PRIMARY KEY (`idmember_manager`),
  INDEX `fk_member_manager_mall1_idx` (`mall_idmall` ASC),
  CONSTRAINT `fk_member_manager_mall1`
    FOREIGN KEY (`mall_idmall`)
    REFERENCES `mydb`.`mall` (`idmall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shoppinglist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shoppinglist` (
  `idshoppinglist` INT NOT NULL COMMENT '																							',
  `member_customer_idmember_customer` INT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idshoppinglist`),
  INDEX `fk_shoppinglist_member_customer1_idx` (`member_customer_idmember_customer` ASC),
  INDEX `fk_shoppinglist_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_shoppinglist_member_customer1`
    FOREIGN KEY (`member_customer_idmember_customer`)
    REFERENCES `mydb`.`member_customer` (`idmember_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppinglist_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `idsession` INT NOT NULL,
  `useid` INT NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`idsession`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
